### Test/Train Split and Encoding

In [69]:
import sys
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from tabulate import tabulate
import miceforest as mf

In [48]:
# Elizabeth Greenan

In [50]:
# Used newly cleaned data file
e_cigarette_data = pd.read_csv("../Data/cleaned_data.csv")
e_cigarette_data.head()

,Unnamed: 0,BMI,Number_of_Children,Dentist_Visit_Last_Year,Health_Insurance,Lung_Cancer_Suspected_Risk,Marijuana_Use_30_Days,Medical_Visit_Missed_Due_to_Cost,Number_of_Days_Last_Month_Poor_Health,High_Financial_Stress_Burden,...,Health_Rating,Annual_Income,Days_Poor_Physical_Health,Education,Social_Emotional_Support,General_Health_Personal_Rating,Life_Satisfaction,Marital_Status,Sugar_Soda_Drinks_Per_Day,Non_Soda_Sugar_Drinks_Per_Day
0,0,22.49,0.0,1.0,1.0,NaN,NaN,0.0,0.0,0.0,...,Good_or_Better_Health,Unknown,1-13_Days,Grade_12_or_GED_(high_school_graduate,Always,Good,Very_satisfied,Widowed,NaN,NaN
1,1,25.83,0.0,1.0,1.0,NaN,NaN,0.0,NaN,0.0,...,Good_or_Better_Health,"$200,000+",0_Days,College_4_years_or_more_(college_graduate),Always,Excellent,Very_satisfied,Married,NaN,NaN
2,2,22.53,0.0,0.0,1.0,NaN,NaN,1.0,1.0,0.0,...,Good_or_Better_Health,Unknown,14+_Days,College_1-3_years_(some_college_or_technical_s...,Usually,Very_good,Very_satisfied,Member_of_unmarried_couple,NaN,NaN
3,3,25.09,0.0,1.0,1.0,NaN,NaN,0.0,NaN,0.0,...,Good_or_Better_Health,"Less_than_$50,000",0_Days,College_4_years_or_more_(college_graduate),Always,Excellent,Very_satisfied,Married,NaN,NaN
4,4,19.77,0.0,1.0,1.0,0.0,NaN,0.0,NaN,0.0,...,Good_or_Better_Health,"Less_than_$20,000",0_Days,College_1-3_years_(some_college_or_technical_s...,Rarely,Good,Satisfied,Never_Married,NaN,NaN

In [52]:
# # Check if target variable has any missing values
e_cols_with_na = e_cigarette_data.columns[e_cigarette_data.isna().any()].tolist()

print(e_cols_with_na)

['BMI', 'Number_of_Children', 'Dentist_Visit_Last_Year', 'Health_Insurance', 'Lung_Cancer_Suspected_Risk', 'Marijuana_Use_30_Days', 'Medical_Visit_Missed_Due_to_Cost', 'Number_of_Days_Last_Month_Poor_Health', 'High_Financial_Stress_Burden', 'Has_Disability', 'Diabetic_History', 'E_Cig_User', 'Total_Drinks_30_days', 'Exercise_Outside_Work_Past_Month', 'Sugar_Soda_Drinks_Per_Day', 'Non_Soda_Sugar_Drinks_Per_Day']

In [54]:
# Removing target variable missing values
e_cigarette_data = e_cigarette_data.dropna(subset=['E_Cig_User'])

In [56]:
# Checking to make sure it was removed
e_cigarette_data['E_Cig_User'].isnull().any()

False

In [57]:
# Remove the Unnamed: 0 field
e_cigarette_data = e_cigarette_data.drop(columns=['Unnamed: 0'])
e_cigarette_data.head()

,BMI,Number_of_Children,Dentist_Visit_Last_Year,Health_Insurance,Lung_Cancer_Suspected_Risk,Marijuana_Use_30_Days,Medical_Visit_Missed_Due_to_Cost,Number_of_Days_Last_Month_Poor_Health,High_Financial_Stress_Burden,Sex,...,Health_Rating,Annual_Income,Days_Poor_Physical_Health,Education,Social_Emotional_Support,General_Health_Personal_Rating,Life_Satisfaction,Marital_Status,Sugar_Soda_Drinks_Per_Day,Non_Soda_Sugar_Drinks_Per_Day
0,22.49,0.0,1.0,1.0,NaN,NaN,0.0,0.0,0.0,Female,...,Good_or_Better_Health,Unknown,1-13_Days,Grade_12_or_GED_(high_school_graduate,Always,Good,Very_satisfied,Widowed,NaN,NaN
1,25.83,0.0,1.0,1.0,NaN,NaN,0.0,NaN,0.0,Male,...,Good_or_Better_Health,"$200,000+",0_Days,College_4_years_or_more_(college_graduate),Always,Excellent,Very_satisfied,Married,NaN,NaN
2,22.53,0.0,0.0,1.0,NaN,NaN,1.0,1.0,0.0,Male,...,Good_or_Better_Health,Unknown,14+_Days,College_1-3_years_(some_college_or_technical_s...,Usually,Very_good,Very_satisfied,Member_of_unmarried_couple,NaN,NaN
3,25.09,0.0,1.0,1.0,NaN,NaN,0.0,NaN,0.0,Male,...,Good_or_Better_Health,"Less_than_$50,000",0_Days,College_4_years_or_more_(college_graduate),Always,Excellent,Very_satisfied,Married,NaN,NaN
4,19.77,0.0,1.0,1.0,0.0,NaN,0.0,NaN,0.0,Male,...,Good_or_Better_Health,"Less_than_$20,000",0_Days,College_1-3_years_(some_college_or_technical_s...,Rarely,Good,Satisfied,Never_Married,NaN,NaN

In [58]:
# Check dimensions
e_cigarette_data.shape

(424919, 31)

In [59]:
# Check columns
print(e_cigarette_data.columns)

Index(['BMI', 'Number_of_Children', 'Dentist_Visit_Last_Year',
       'Health_Insurance', 'Lung_Cancer_Suspected_Risk',
       'Marijuana_Use_30_Days', 'Medical_Visit_Missed_Due_to_Cost',
       'Number_of_Days_Last_Month_Poor_Health', 'High_Financial_Stress_Burden',
       'Sex', 'Has_Disability', 'Diabetic_History', 'Days_Poor_Mental_Health',
       'Age_Category', 'E_Cig_User', 'Other_Tobacco_Usage', 'Race',
       'Total_Drinks_30_days', 'Time_Since_Last_Check_Up',
       'Exercise_Outside_Work_Past_Month', 'Loneliness', 'Health_Rating',
       'Annual_Income', 'Days_Poor_Physical_Health', 'Education',
       'Social_Emotional_Support', 'General_Health_Personal_Rating',
       'Life_Satisfaction', 'Marital_Status', 'Sugar_Soda_Drinks_Per_Day',
       'Non_Soda_Sugar_Drinks_Per_Day'],
      dtype='object')

In [60]:
# Move the target/response variable (E_Cig_User) to the end of the dataframe
# Source: https://stackoverflow.com/questions/72782872/move-a-dataframe-column-to-last-column
e_cigarette_data['E_Cig_User'] = e_cigarette_data.pop('E_Cig_User')

In [61]:
# Make sure E_Cig_User is last variable
print(e_cigarette_data.columns)

Index(['BMI', 'Number_of_Children', 'Dentist_Visit_Last_Year',
       'Health_Insurance', 'Lung_Cancer_Suspected_Risk',
       'Marijuana_Use_30_Days', 'Medical_Visit_Missed_Due_to_Cost',
       'Number_of_Days_Last_Month_Poor_Health', 'High_Financial_Stress_Burden',
       'Sex', 'Has_Disability', 'Diabetic_History', 'Days_Poor_Mental_Health',
       'Age_Category', 'Other_Tobacco_Usage', 'Race', 'Total_Drinks_30_days',
       'Time_Since_Last_Check_Up', 'Exercise_Outside_Work_Past_Month',
       'Loneliness', 'Health_Rating', 'Annual_Income',
       'Days_Poor_Physical_Health', 'Education', 'Social_Emotional_Support',
       'General_Health_Personal_Rating', 'Life_Satisfaction', 'Marital_Status',
       'Sugar_Soda_Drinks_Per_Day', 'Non_Soda_Sugar_Drinks_Per_Day',
       'E_Cig_User'],
      dtype='object')

In [62]:
# Check dimensions
e_cigarette_data.shape

(424919, 31)

In [63]:
# Test/Train Split source: Used code Professor Geist provided (calcSplitRatio.py)

In [64]:
# p represents the number of parameters
def calcSplitRatio(e_cigarette_data, p = None):
    if p is None:
        p = e_cigarette_data.shape[1] - 1 # This assumes the last column is the target variable

    # Calculate the ideal number for the testing set
    test_N = (1 / np.sqrt(p)) * len(e_cigarette_data)

    # Calculate the testing proportion
    test_prop = round(test_N / len(e_cigarette_data), 2)

    # Calculate the training proportion
    train_prop = 1 - test_prop

    # Print the results
    print(f"The ideal split ratio is {train_prop}:{test_prop} training:testing")

    # Return the size of the training set proportion
    return train_prop

In [65]:
train_prop = calcSplitRatio(e_cigarette_data)

The ideal split ratio is 0.8200000000000001:0.18 training:testing

In [66]:
# The training proportion is 82% and the testing proportion is 18%.

## Supervised Test/Train Split

In [21]:
# Code source: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
# Referenced code from previous course (DSE6211: Lab 2)

# Remove the response variable
x = e_cigarette_data.drop('E_Cig_User', axis = 1)
# Want to predict the response variable
y = e_cigarette_data['E_Cig_User']
# Perform test/train split
# Random_state ensures reproducibility
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = train_prop, random_state = 1)

## Unsupervised Test/Train Split

In [22]:
# Since unsupervised does not use a response variable, the y code was removed
# Remove the response variable
x = e_cigarette_data.drop('E_Cig_User', axis = 1)
# Perform test/train split
# Random_state ensures reproducibility
x_train_unsupervised, x_test_unsupervised = train_test_split(x, train_size = train_prop, random_state = 1)

## Check results of split to ensure they are correct

In [23]:
print(x_train.shape)
print(x_test.shape)

(348433, 30)
(76486, 30)

In [24]:
print(y_train.shape)
print(y_test.shape)

(348433,)
(76486,)

In [25]:
# Confirm that the training set is approximately 82% and the test set is approximately 18%
training_ratio = len(x_train) / (len(x_train) + len(x_test))
test_ratio = len(x_test) / len(x)

print("Training ratio:", training_ratio)
print("Test ratio:", test_ratio)

Training ratio: 0.8199986350339712
Test ratio: 0.1800013649660288

In [26]:
# Confirm there is one less column, due to the removal of the response variable
x_train.head()

,BMI,Number_of_Children,Dentist_Visit_Last_Year,Health_Insurance,Lung_Cancer_Suspected_Risk,Marijuana_Use_30_Days,Medical_Visit_Missed_Due_to_Cost,Number_of_Days_Last_Month_Poor_Health,High_Financial_Stress_Burden,Sex,...,Health_Rating,Annual_Income,Days_Poor_Physical_Health,Education,Social_Emotional_Support,General_Health_Personal_Rating,Life_Satisfaction,Marital_Status,Sugar_Soda_Drinks_Per_Day,Non_Soda_Sugar_Drinks_Per_Day
294665,23.73,1.0,1.0,1.0,NaN,NaN,0.0,0.0,NaN,Male,...,Good_or_Better_Health,"Less_than_$200,000",0_Days,College_4_years_or_more_(college_graduate),Unknown,Excellent,Unknown,Married,NaN,NaN
304948,20.50,0.0,1.0,1.0,1.0,NaN,0.0,NaN,0.0,Female,...,Good_or_Better_Health,"Less_than_$200,000",0_Days,College_4_years_or_more_(college_graduate),Always,Very_good,Very_satisfied,Married,1.0,1.0
171185,27.94,0.0,0.0,1.0,NaN,NaN,0.0,5.0,NaN,Male,...,Fair_or_Poor_Health,Unknown,1-13_Days,Grades_1-8_(elementary),Unknown,Fair,Unknown,Widowed,NaN,NaN
99327,33.77,0.0,1.0,1.0,0.0,0.0,0.0,7.0,NaN,Male,...,Good_or_Better_Health,"Less_than_$150,000",1-13_Days,College_4_years_or_more_(college_graduate),Unknown,Good,Unknown,Married,NaN,NaN
21252,37.66,0.0,0.0,1.0,0.0,NaN,1.0,25.0,1.0,Male,...,Fair_or_Poor_Health,"Less_than_$15,000",14+_Days,College_1-3_years_(some_college_or_technical_s...,Rarely,Poor,Dissatisfied,Member_of_unmarried_couple,NaN,NaN

## MICE Imputation

In [27]:
# Kevin Wilson

In [28]:
x_train.dtypes

BMI                                      float64
Number_of_Children                       float64
Dentist_Visit_Last_Year                  float64
Health_Insurance                         float64
Lung_Cancer_Suspected_Risk               float64
Marijuana_Use_30_Days                    float64
Medical_Visit_Missed_Due_to_Cost         float64
Number_of_Days_Last_Month_Poor_Health    float64
High_Financial_Stress_Burden             float64
Sex                                       object
Has_Disability                           float64
Diabetic_History                         float64
Days_Poor_Mental_Health                   object
Age_Category                              object
Other_Tobacco_Usage                       object
Race                                      object
Total_Drinks_30_days                     float64
Time_Since_Last_Check_Up                  object
Exercise_Outside_Work_Past_Month         float64
Loneliness                                object
Health_Rating                             object
Annual_Income                             object
Days_Poor_Physical_Health                 object
Education                                 object
Social_Emotional_Support                  object
General_Health_Personal_Rating            object
Life_Satisfaction                         object
Marital_Status                            object
Sugar_Soda_Drinks_Per_Day                float64
Non_Soda_Sugar_Drinks_Per_Day            float64
dtype: object

In [29]:
x_train[['Sex', 'Days_Poor_Mental_Health', 'Age_Category', 'Other_Tobacco_Usage', 'Race', 'Time_Since_Last_Check_Up', 'Loneliness', 'Health_Rating', 'Annual_Income', 'Days_Poor_Physical_Health', 'Education', 'Social_Emotional_Support', 'General_Health_Personal_Rating', 'Life_Satisfaction', 'Marital_Status']] = x_train[['Sex', 'Days_Poor_Mental_Health', 'Age_Category', 'Other_Tobacco_Usage', 'Race', 'Time_Since_Last_Check_Up', 'Loneliness', 'Health_Rating', 'Annual_Income', 'Days_Poor_Physical_Health', 'Education', 'Social_Emotional_Support', 'General_Health_Personal_Rating', 'Life_Satisfaction', 'Marital_Status']].astype('category')

x_train = x_train.reset_index(drop=True)

# Create kernel
kernel = mf.ImputationKernel(x_train, num_datasets=4)

# Run MICE
kernel.mice(3)

# Return completed data
x_train_imputed = kernel.complete_data()

In [30]:
x_test[['Sex', 'Days_Poor_Mental_Health', 'Age_Category', 'Other_Tobacco_Usage', 'Race', 
        'Time_Since_Last_Check_Up', 'Loneliness', 'Health_Rating', 'Annual_Income', 
        'Days_Poor_Physical_Health', 'Education', 'Social_Emotional_Support', 
        'General_Health_Personal_Rating', 'Life_Satisfaction', 'Marital_Status']] = (
    x_test[['Sex', 'Days_Poor_Mental_Health', 'Age_Category', 'Other_Tobacco_Usage', 'Race', 
            'Time_Since_Last_Check_Up', 'Loneliness', 'Health_Rating', 'Annual_Income', 
            'Days_Poor_Physical_Health', 'Education', 'Social_Emotional_Support', 
            'General_Health_Personal_Rating', 'Life_Satisfaction', 'Marital_Status']]
    .astype('category')
)

x_test = x_test.reset_index(drop=True)

# Use the trained kernel to impute the test set
test_kernel = kernel.impute_new_data(x_test)

# Return completed test data
x_test_imputed = test_kernel.complete_data()

In [31]:
# Checking that MICE worked

In [32]:
x_train_check = x_train_imputed.columns[x_train_imputed.isna().any()].tolist()
print(x_train_check)

[]

In [33]:
x_test_check = x_test_imputed.columns[x_test_imputed.isna().any()].tolist()
print(x_test_check)

[]

## One-Hot Encoding

In [34]:
# Elizabeth Greenan

In [35]:
# Check data types
x_train_imputed.dtypes

BMI                                       float64
Number_of_Children                        float64
Dentist_Visit_Last_Year                   float64
Health_Insurance                          float64
Lung_Cancer_Suspected_Risk                float64
Marijuana_Use_30_Days                     float64
Medical_Visit_Missed_Due_to_Cost          float64
Number_of_Days_Last_Month_Poor_Health     float64
High_Financial_Stress_Burden              float64
Sex                                      category
Has_Disability                            float64
Diabetic_History                          float64
Days_Poor_Mental_Health                  category
Age_Category                             category
Other_Tobacco_Usage                      category
Race                                     category
Total_Drinks_30_days                      float64
Time_Since_Last_Check_Up                 category
Exercise_Outside_Work_Past_Month          float64
Loneliness                               category
Health_Rating                            category
Annual_Income                            category
Days_Poor_Physical_Health                category
Education                                category
Social_Emotional_Support                 category
General_Health_Personal_Rating           category
Life_Satisfaction                        category
Marital_Status                           category
Sugar_Soda_Drinks_Per_Day                 float64
Non_Soda_Sugar_Drinks_Per_Day             float64
dtype: object

In [36]:
# Check data types
x_test_imputed.dtypes

BMI                                       float64
Number_of_Children                        float64
Dentist_Visit_Last_Year                   float64
Health_Insurance                          float64
Lung_Cancer_Suspected_Risk                float64
Marijuana_Use_30_Days                     float64
Medical_Visit_Missed_Due_to_Cost          float64
Number_of_Days_Last_Month_Poor_Health     float64
High_Financial_Stress_Burden              float64
Sex                                      category
Has_Disability                            float64
Diabetic_History                          float64
Days_Poor_Mental_Health                  category
Age_Category                             category
Other_Tobacco_Usage                      category
Race                                     category
Total_Drinks_30_days                      float64
Time_Since_Last_Check_Up                 category
Exercise_Outside_Work_Past_Month          float64
Loneliness                               category
Health_Rating                            category
Annual_Income                            category
Days_Poor_Physical_Health                category
Education                                category
Social_Emotional_Support                 category
General_Health_Personal_Rating           category
Life_Satisfaction                        category
Marital_Status                           category
Sugar_Soda_Drinks_Per_Day                 float64
Non_Soda_Sugar_Drinks_Per_Day             float64
dtype: object

In [37]:
# Create list of categorical variables for one-hot encoding
categorical_var = ['Sex', 'Days_Poor_Mental_Health', 'Age_Category', 'Other_Tobacco_Usage', 'Race', 'Time_Since_Last_Check_Up', 'Loneliness', 'Health_Rating', 'Annual_Income', 'Days_Poor_Physical_Health', 'Education', 'Social_Emotional_Support', 'General_Health_Personal_Rating', 'Life_Satisfaction', 'Marital_Status']
# One-Hot Encoding on Training Set
encoder = OneHotEncoder(handle_unknown = 'ignore')
encoder.fit(x_train_imputed[categorical_var])
encoded_train = pd.DataFrame(
    encoder.transform(x_train_imputed[categorical_var]).toarray(),
    columns = encoder.get_feature_names_out(categorical_var))
x_train_imputed = pd.concat([x_train_imputed.drop(columns = categorical_var), encoded_train], axis = 1)
x_train_imputed.columns

Index(['BMI', 'Number_of_Children', 'Dentist_Visit_Last_Year',
       'Health_Insurance', 'Lung_Cancer_Suspected_Risk',
       'Marijuana_Use_30_Days', 'Medical_Visit_Missed_Due_to_Cost',
       'Number_of_Days_Last_Month_Poor_Health', 'High_Financial_Stress_Burden',
       'Has_Disability', 'Diabetic_History', 'Total_Drinks_30_days',
       'Exercise_Outside_Work_Past_Month', 'Sugar_Soda_Drinks_Per_Day',
       'Non_Soda_Sugar_Drinks_Per_Day', 'Sex_Female', 'Sex_Male',
       'Days_Poor_Mental_Health_0_Days', 'Days_Poor_Mental_Health_1-13_Days',
       'Days_Poor_Mental_Health_14+_Days', 'Days_Poor_Mental_Health_Unknown',
       'Age_Category_Elderly', 'Age_Category_Middle_Aged',
       'Age_Category_Unknown', 'Age_Category_Young_Adult',
       'Other_Tobacco_Usage_Every Day', 'Other_Tobacco_Usage_Not at all',
       'Other_Tobacco_Usage_Some days', 'Other_Tobacco_Usage_Unknown',
       'Race_American Indian or Alaskan Native', 'Race_Asian', 'Race_Black',
       'Race_Hispanic', 'Race_Multiracial',
       'Race_Native Hawaiian or other Pacific Islander', 'Race_Other Race',
       'Race_Unknown', 'Race_White',
       'Time_Since_Last_Check_Up_Five_or_more_years_ago',
       'Time_Since_Last_Check_Up_Never', 'Time_Since_Last_Check_Up_Unknown',
       'Time_Since_Last_Check_Up_Within_the_last_year',
       'Time_Since_Last_Check_Up_Within_the_past_five_years',
       'Time_Since_Last_Check_Up_Within_the_past_two_years',
       'Loneliness_Always', 'Loneliness_Never', 'Loneliness_Rarely',
       'Loneliness_Sometimes', 'Loneliness_Unknown', 'Loneliness_Usually',
       'Health_Rating_Fair_or_Poor_Health',
       'Health_Rating_Good_or_Better_Health', 'Health_Rating_Unknown',
       'Annual_Income_$200,000+', 'Annual_Income_Less_than_$10,000',
       'Annual_Income_Less_than_$100,000', 'Annual_Income_Less_than_$15,000',
       'Annual_Income_Less_than_$150,000', 'Annual_Income_Less_than_$20,000',
       'Annual_Income_Less_than_$200,000', 'Annual_Income_Less_than_$25,000',
       'Annual_Income_Less_than_$35,000', 'Annual_Income_Less_than_$50,000',
       'Annual_Income_Less_than_$75,000', 'Annual_Income_Unknown',
       'Days_Poor_Physical_Health_0_Days',
       'Days_Poor_Physical_Health_1-13_Days',
       'Days_Poor_Physical_Health_14+_Days',
       'Days_Poor_Physical_Health_Unknown',
       'Education_College_1-3_years_(some_college_or_technical_school',
       'Education_College_4_years_or_more_(college_graduate)',
       'Education_Grade_12_or_GED_(high_school_graduate',
       'Education_Grades_1-8_(elementary)',
       'Education_Grades_9-11_(some_high_school)',
       'Education_Never_attended_school_or_only_Kindergarten',
       'Education_Unknown', 'Social_Emotional_Support_Always',
       'Social_Emotional_Support_Never', 'Social_Emotional_Support_Rarely',
       'Social_Emotional_Support_Sometimes',
       'Social_Emotional_Support_Unknown', 'Social_Emotional_Support_Usually',
       'General_Health_Personal_Rating_Excellent',
       'General_Health_Personal_Rating_Fair',
       'General_Health_Personal_Rating_Good',
       'General_Health_Personal_Rating_Poor',
       'General_Health_Personal_Rating_Unknown',
       'General_Health_Personal_Rating_Very_good',
       'Life_Satisfaction_Dissatisfied', 'Life_Satisfaction_Satisfied',
       'Life_Satisfaction_Unknown', 'Life_Satisfaction_Very_dissatified',
       'Life_Satisfaction_Very_satisfied', 'Marital_Status_Divorced',
       'Marital_Status_Married', 'Marital_Status_Member_of_unmarried_couple',
       'Marital_Status_Never_Married', 'Marital_Status_Separated',
       'Marital_Status_Unknown', 'Marital_Status_Widowed'],
      dtype='object')

In [38]:
# One-Hot Encoding on Test Set
encoded_test = pd.DataFrame(
    encoder.transform(x_test_imputed[categorical_var]).toarray(),
    columns = encoder.get_feature_names_out(categorical_var))
x_test_imputed = pd.concat([x_test_imputed.drop(columns = categorical_var), encoded_test], axis = 1)
x_test_imputed.columns

Index(['BMI', 'Number_of_Children', 'Dentist_Visit_Last_Year',
       'Health_Insurance', 'Lung_Cancer_Suspected_Risk',
       'Marijuana_Use_30_Days', 'Medical_Visit_Missed_Due_to_Cost',
       'Number_of_Days_Last_Month_Poor_Health', 'High_Financial_Stress_Burden',
       'Has_Disability', 'Diabetic_History', 'Total_Drinks_30_days',
       'Exercise_Outside_Work_Past_Month', 'Sugar_Soda_Drinks_Per_Day',
       'Non_Soda_Sugar_Drinks_Per_Day', 'Sex_Female', 'Sex_Male',
       'Days_Poor_Mental_Health_0_Days', 'Days_Poor_Mental_Health_1-13_Days',
       'Days_Poor_Mental_Health_14+_Days', 'Days_Poor_Mental_Health_Unknown',
       'Age_Category_Elderly', 'Age_Category_Middle_Aged',
       'Age_Category_Unknown', 'Age_Category_Young_Adult',
       'Other_Tobacco_Usage_Every Day', 'Other_Tobacco_Usage_Not at all',
       'Other_Tobacco_Usage_Some days', 'Other_Tobacco_Usage_Unknown',
       'Race_American Indian or Alaskan Native', 'Race_Asian', 'Race_Black',
       'Race_Hispanic', 'Race_Multiracial',
       'Race_Native Hawaiian or other Pacific Islander', 'Race_Other Race',
       'Race_Unknown', 'Race_White',
       'Time_Since_Last_Check_Up_Five_or_more_years_ago',
       'Time_Since_Last_Check_Up_Never', 'Time_Since_Last_Check_Up_Unknown',
       'Time_Since_Last_Check_Up_Within_the_last_year',
       'Time_Since_Last_Check_Up_Within_the_past_five_years',
       'Time_Since_Last_Check_Up_Within_the_past_two_years',
       'Loneliness_Always', 'Loneliness_Never', 'Loneliness_Rarely',
       'Loneliness_Sometimes', 'Loneliness_Unknown', 'Loneliness_Usually',
       'Health_Rating_Fair_or_Poor_Health',
       'Health_Rating_Good_or_Better_Health', 'Health_Rating_Unknown',
       'Annual_Income_$200,000+', 'Annual_Income_Less_than_$10,000',
       'Annual_Income_Less_than_$100,000', 'Annual_Income_Less_than_$15,000',
       'Annual_Income_Less_than_$150,000', 'Annual_Income_Less_than_$20,000',
       'Annual_Income_Less_than_$200,000', 'Annual_Income_Less_than_$25,000',
       'Annual_Income_Less_than_$35,000', 'Annual_Income_Less_than_$50,000',
       'Annual_Income_Less_than_$75,000', 'Annual_Income_Unknown',
       'Days_Poor_Physical_Health_0_Days',
       'Days_Poor_Physical_Health_1-13_Days',
       'Days_Poor_Physical_Health_14+_Days',
       'Days_Poor_Physical_Health_Unknown',
       'Education_College_1-3_years_(some_college_or_technical_school',
       'Education_College_4_years_or_more_(college_graduate)',
       'Education_Grade_12_or_GED_(high_school_graduate',
       'Education_Grades_1-8_(elementary)',
       'Education_Grades_9-11_(some_high_school)',
       'Education_Never_attended_school_or_only_Kindergarten',
       'Education_Unknown', 'Social_Emotional_Support_Always',
       'Social_Emotional_Support_Never', 'Social_Emotional_Support_Rarely',
       'Social_Emotional_Support_Sometimes',
       'Social_Emotional_Support_Unknown', 'Social_Emotional_Support_Usually',
       'General_Health_Personal_Rating_Excellent',
       'General_Health_Personal_Rating_Fair',
       'General_Health_Personal_Rating_Good',
       'General_Health_Personal_Rating_Poor',
       'General_Health_Personal_Rating_Unknown',
       'General_Health_Personal_Rating_Very_good',
       'Life_Satisfaction_Dissatisfied', 'Life_Satisfaction_Satisfied',
       'Life_Satisfaction_Unknown', 'Life_Satisfaction_Very_dissatified',
       'Life_Satisfaction_Very_satisfied', 'Marital_Status_Divorced',
       'Marital_Status_Married', 'Marital_Status_Member_of_unmarried_couple',
       'Marital_Status_Never_Married', 'Marital_Status_Separated',
       'Marital_Status_Unknown', 'Marital_Status_Widowed'],
      dtype='object')

In [39]:
# Check that the columns in both training and test set match
set(x_train_imputed.columns) == set(x_test_imputed.columns)

True

In [40]:
# Check that the columns in both training and test set match
set(x_train_unsupervised.columns) == set(x_test_unsupervised.columns)

True

## Center and Scale variables

In [41]:
# Kevin Wilson
# Source: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

In [42]:
scaler = StandardScaler()

scaler.fit(x_train_imputed)
x_train_scaled = pd.DataFrame(scaler.transform(x_train_imputed), columns = x_train_imputed.columns)
x_test_scaled = pd.DataFrame(scaler.transform(x_test_imputed), columns = x_test_imputed.columns)

## Export pre-processed data as CSV files to be used in models

In [43]:
# Elizabeth Greenan
# Source: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html

In [44]:
x_train_scaled.to_csv("../Data/x_train.csv", index = False)
x_test_scaled.to_csv("../Data/x_test.csv", index = False)

In [45]:
y_train.to_csv("../Data/y_train.csv", index = False)
y_test.to_csv("../Data/y_test.csv", index = False)