### Test/Train Split and Encoding

In [54]:
import sys
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from tabulate import tabulate
import miceforest as mf

In [55]:
# Elizabeth Greenan

In [56]:
import os
print(os.getcwd())

/Users/elizabethgreenan/Documents/DSE6311/GitHub/DSE6311/E-Cigarette-Health-Advertisement-Study/Scripts

In [57]:
# Use newly cleaned data from Nick from 4/11
e_cigarette_data = pd.read_csv("../Data/cleaned_data.csv")
e_cigarette_data.head()

,Unnamed: 0,BMI,Number_of_Children,Dentist_Visit_Last_Year,Health_Insurance,Lung_Cancer_Suspected_Risk,Marijuana_Use_30_Days,Medical_Visit_Missed_Due_to_Cost,Number_of_Days_Last_Month_Poor_Health,High_Financial_Stress_Burden,...,Social_Emotional_Support,General_Health_Personal_Rating,Life_Satisfaction,Marital_Status,Sugar_Soda_Drinks_Per_Day,Sugar_Soda_Drinks_Per_Week,Sugar_Soda_Drinks_Per_Month,Non_Soda_Sugar_Drinks_Per_Day,Non_Soda_Sugar_Drinks_Per_Week,Non_Soda_Sugar_Drinks_Per_Month
0,0,22.49,0.0,1.0,1.0,NaN,NaN,0.0,0.0,0.0,...,Always,Good,Very_satisfied,Widowed,NaN,NaN,NaN,NaN,NaN,NaN
1,1,25.83,0.0,1.0,1.0,NaN,NaN,0.0,NaN,0.0,...,Always,Excellent,Very_satisfied,Married,NaN,NaN,NaN,NaN,NaN,NaN
2,2,22.53,0.0,0.0,1.0,NaN,NaN,1.0,1.0,0.0,...,Usually,Very_good,Very_satisfied,Member_of_unmarried_couple,NaN,NaN,NaN,NaN,NaN,NaN
3,3,25.09,0.0,1.0,1.0,NaN,NaN,0.0,NaN,0.0,...,Always,Excellent,Very_satisfied,Married,NaN,NaN,NaN,NaN,NaN,NaN
4,4,19.77,0.0,1.0,1.0,0.0,NaN,0.0,NaN,0.0,...,Rarely,Good,Satisfied,Never_Married,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
# Added to see if target variable was missing any values

In [59]:
e_cols_with_na = e_cigarette_data.columns[e_cigarette_data.isna().any()].tolist()

print(e_cols_with_na)

['BMI', 'Number_of_Children', 'Dentist_Visit_Last_Year', 'Health_Insurance', 'Lung_Cancer_Suspected_Risk', 'Marijuana_Use_30_Days', 'Medical_Visit_Missed_Due_to_Cost', 'Number_of_Days_Last_Month_Poor_Health', 'High_Financial_Stress_Burden', 'Has_Disability', 'Diabetic_History', 'E_Cig_User', 'Total_Drinks_30_days', 'Exercise_Outside_Work_Past_Month', 'Sugar_Soda_Drinks_Per_Day', 'Sugar_Soda_Drinks_Per_Week', 'Sugar_Soda_Drinks_Per_Month', 'Non_Soda_Sugar_Drinks_Per_Day', 'Non_Soda_Sugar_Drinks_Per_Week', 'Non_Soda_Sugar_Drinks_Per_Month']

In [60]:
# Removing target variable missing values

In [61]:
e_cigarette_data = e_cigarette_data.dropna(subset=['E_Cig_User'])

In [62]:
# Checking to make sure it was removed

In [63]:
e_cigarette_data['E_Cig_User'].isnull().any()

False

In [64]:
# Remove the Unnamed: 0 field
e_cigarette_data = e_cigarette_data.drop(columns=['Unnamed: 0'])
e_cigarette_data.head()

,BMI,Number_of_Children,Dentist_Visit_Last_Year,Health_Insurance,Lung_Cancer_Suspected_Risk,Marijuana_Use_30_Days,Medical_Visit_Missed_Due_to_Cost,Number_of_Days_Last_Month_Poor_Health,High_Financial_Stress_Burden,Sex,...,Social_Emotional_Support,General_Health_Personal_Rating,Life_Satisfaction,Marital_Status,Sugar_Soda_Drinks_Per_Day,Sugar_Soda_Drinks_Per_Week,Sugar_Soda_Drinks_Per_Month,Non_Soda_Sugar_Drinks_Per_Day,Non_Soda_Sugar_Drinks_Per_Week,Non_Soda_Sugar_Drinks_Per_Month
0,22.49,0.0,1.0,1.0,NaN,NaN,0.0,0.0,0.0,Female,...,Always,Good,Very_satisfied,Widowed,NaN,NaN,NaN,NaN,NaN,NaN
1,25.83,0.0,1.0,1.0,NaN,NaN,0.0,NaN,0.0,Male,...,Always,Excellent,Very_satisfied,Married,NaN,NaN,NaN,NaN,NaN,NaN
2,22.53,0.0,0.0,1.0,NaN,NaN,1.0,1.0,0.0,Male,...,Usually,Very_good,Very_satisfied,Member_of_unmarried_couple,NaN,NaN,NaN,NaN,NaN,NaN
3,25.09,0.0,1.0,1.0,NaN,NaN,0.0,NaN,0.0,Male,...,Always,Excellent,Very_satisfied,Married,NaN,NaN,NaN,NaN,NaN,NaN
4,19.77,0.0,1.0,1.0,0.0,NaN,0.0,NaN,0.0,Male,...,Rarely,Good,Satisfied,Never_Married,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
e_cigarette_data.shape

(424919, 35)

In [66]:
print(e_cigarette_data.columns)

Index(['BMI', 'Number_of_Children', 'Dentist_Visit_Last_Year',
       'Health_Insurance', 'Lung_Cancer_Suspected_Risk',
       'Marijuana_Use_30_Days', 'Medical_Visit_Missed_Due_to_Cost',
       'Number_of_Days_Last_Month_Poor_Health', 'High_Financial_Stress_Burden',
       'Sex', 'Has_Disability', 'Diabetic_History', 'Days_Poor_Mental_Health',
       'Age_Category', 'E_Cig_User', 'Other_Tobacco_Usage', 'Race',
       'Total_Drinks_30_days', 'Time_Since_Last_Check_Up',
       'Exercise_Outside_Work_Past_Month', 'Loneliness', 'Health_Rating',
       'Annual_Income', 'Days_Poor_Physical_Health', 'Education',
       'Social_Emotional_Support', 'General_Health_Personal_Rating',
       'Life_Satisfaction', 'Marital_Status', 'Sugar_Soda_Drinks_Per_Day',
       'Sugar_Soda_Drinks_Per_Week', 'Sugar_Soda_Drinks_Per_Month',
       'Non_Soda_Sugar_Drinks_Per_Day', 'Non_Soda_Sugar_Drinks_Per_Week',
       'Non_Soda_Sugar_Drinks_Per_Month'],
      dtype='object')

In [67]:
# Move the target/response varaible (E_Cig_User) to the end of the dataframe
# Source: https://stackoverflow.com/questions/72782872/move-a-dataframe-column-to-last-column
e_cigarette_data['E_Cig_User'] = e_cigarette_data.pop('E_Cig_User')

In [68]:
print(e_cigarette_data.columns)

Index(['BMI', 'Number_of_Children', 'Dentist_Visit_Last_Year',
       'Health_Insurance', 'Lung_Cancer_Suspected_Risk',
       'Marijuana_Use_30_Days', 'Medical_Visit_Missed_Due_to_Cost',
       'Number_of_Days_Last_Month_Poor_Health', 'High_Financial_Stress_Burden',
       'Sex', 'Has_Disability', 'Diabetic_History', 'Days_Poor_Mental_Health',
       'Age_Category', 'Other_Tobacco_Usage', 'Race', 'Total_Drinks_30_days',
       'Time_Since_Last_Check_Up', 'Exercise_Outside_Work_Past_Month',
       'Loneliness', 'Health_Rating', 'Annual_Income',
       'Days_Poor_Physical_Health', 'Education', 'Social_Emotional_Support',
       'General_Health_Personal_Rating', 'Life_Satisfaction', 'Marital_Status',
       'Sugar_Soda_Drinks_Per_Day', 'Sugar_Soda_Drinks_Per_Week',
       'Sugar_Soda_Drinks_Per_Month', 'Non_Soda_Sugar_Drinks_Per_Day',
       'Non_Soda_Sugar_Drinks_Per_Week', 'Non_Soda_Sugar_Drinks_Per_Month',
       'E_Cig_User'],
      dtype='object')

In [69]:
e_cigarette_data.shape

(424919, 35)

In [70]:
# Test/Train Split source: Used code Professor Geist provided (calcSplitRatio.py)

In [71]:
# p represents the number of parameters
def calcSplitRatio(e_cigarette_data, p = None):
    if p is None:
        p = e_cigarette_data.shape[1] - 1 # This assumes the last column is the target variable

    # Calculate the ideal number for the testing set
    test_N = (1 / np.sqrt(p)) * len(e_cigarette_data)

    # Calculate the testing proportion
    test_prop = round(test_N / len(e_cigarette_data), 2)

    # Calculate the training proportion
    train_prop = 1 - test_prop

    # Print the results
    print(f"The ideal split ratio is {train_prop}:{test_prop} training:testing")

    # Return the size of the training set proportion
    return train_prop

In [72]:
train_prop = calcSplitRatio(e_cigarette_data)

The ideal split ratio is 0.83:0.17 training:testing

In [73]:
# The training proportion is 83% and the testing proportion is 17%.

## Supervised Test/Train Split

In [74]:
# Code source: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
# Referenced code from DSE6211 (Lab 2)

# Remove the response variable
x = e_cigarette_data.drop('E_Cig_User', axis = 1)
# Want to predict the response variable
y = e_cigarette_data['E_Cig_User']
# Perform test/train split
# Random_state ensures reproducibility
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = train_prop, random_state = 1)

## Unsupervised Test/Train Split

In [75]:
# Since unsupervised does not use a response variable, the y code was removed
# Remove the response variable
x = e_cigarette_data.drop('E_Cig_User', axis = 1)
# Perform test/train split
# Random_state ensures reproducibility
x_train_unsupervised, x_test_unsupervised = train_test_split(x, train_size = train_prop, random_state = 1)

## Check results of split to ensure they are correct

In [76]:
print(x_train.shape)
print(x_test.shape)

(352682, 34)
(72237, 34)

In [77]:
print(y_train.shape)
print(y_test.shape)

(352682,)
(72237,)

In [78]:
# Confirm that the training set is approximately 83% and the test set is approximately 17%
training_ratio = len(x_train) / (len(x_train) + len(x_test))
test_ratio = len(x_test) / len(x)

print("Training ratio:", training_ratio)
print("Test ratio:", test_ratio)

Training ratio: 0.8299981878899273
Test ratio: 0.17000181211007273

In [79]:
# Confirm there is one less column, due to the removal of the response variable
x_train.head()

,BMI,Number_of_Children,Dentist_Visit_Last_Year,Health_Insurance,Lung_Cancer_Suspected_Risk,Marijuana_Use_30_Days,Medical_Visit_Missed_Due_to_Cost,Number_of_Days_Last_Month_Poor_Health,High_Financial_Stress_Burden,Sex,...,Social_Emotional_Support,General_Health_Personal_Rating,Life_Satisfaction,Marital_Status,Sugar_Soda_Drinks_Per_Day,Sugar_Soda_Drinks_Per_Week,Sugar_Soda_Drinks_Per_Month,Non_Soda_Sugar_Drinks_Per_Day,Non_Soda_Sugar_Drinks_Per_Week,Non_Soda_Sugar_Drinks_Per_Month
77155,37.12,0.0,1.0,1.0,1.0,NaN,0.0,0.0,0.0,Female,...,Usually,Good,Very_satisfied,Divorced,NaN,NaN,NaN,NaN,NaN,NaN
26139,34.34,0.0,1.0,1.0,NaN,0.0,0.0,0.0,0.0,Female,...,Always,Poor,Satisfied,Married,NaN,NaN,NaN,NaN,NaN,NaN
12012,24.03,0.0,1.0,1.0,NaN,NaN,0.0,NaN,NaN,Female,...,Unknown,Very_good,Unknown,Married,NaN,NaN,NaN,NaN,NaN,NaN
41422,30.39,1.0,0.0,0.0,NaN,NaN,1.0,0.0,NaN,Female,...,Unknown,Fair,Unknown,Separated,NaN,NaN,NaN,NaN,NaN,NaN
170556,28.29,0.0,1.0,1.0,NaN,NaN,0.0,NaN,NaN,Female,...,Unknown,Fair,Unknown,Divorced,NaN,NaN,NaN,NaN,NaN,NaN

## MICE Imputation

In [80]:
# Kevin Wilson

In [81]:
x_train.dtypes

BMI                                      float64
Number_of_Children                       float64
Dentist_Visit_Last_Year                  float64
Health_Insurance                         float64
Lung_Cancer_Suspected_Risk               float64
Marijuana_Use_30_Days                    float64
Medical_Visit_Missed_Due_to_Cost         float64
Number_of_Days_Last_Month_Poor_Health    float64
High_Financial_Stress_Burden             float64
Sex                                       object
Has_Disability                           float64
Diabetic_History                         float64
Days_Poor_Mental_Health                   object
Age_Category                              object
Other_Tobacco_Usage                       object
Race                                      object
Total_Drinks_30_days                     float64
Time_Since_Last_Check_Up                  object
Exercise_Outside_Work_Past_Month         float64
Loneliness                                object
Health_Rating                             object
Annual_Income                             object
Days_Poor_Physical_Health                 object
Education                                 object
Social_Emotional_Support                  object
General_Health_Personal_Rating            object
Life_Satisfaction                         object
Marital_Status                            object
Sugar_Soda_Drinks_Per_Day                float64
Sugar_Soda_Drinks_Per_Week               float64
Sugar_Soda_Drinks_Per_Month              float64
Non_Soda_Sugar_Drinks_Per_Day            float64
Non_Soda_Sugar_Drinks_Per_Week           float64
Non_Soda_Sugar_Drinks_Per_Month          float64
dtype: object

In [82]:
x_train[['Sex', 'Days_Poor_Mental_Health', 'Age_Category', 'Other_Tobacco_Usage', 'Race', 'Time_Since_Last_Check_Up', 'Loneliness', 'Health_Rating', 'Annual_Income', 'Days_Poor_Physical_Health', 'Education', 'Social_Emotional_Support', 'General_Health_Personal_Rating', 'Life_Satisfaction', 'Marital_Status']] = x_train[['Sex', 'Days_Poor_Mental_Health', 'Age_Category', 'Other_Tobacco_Usage', 'Race', 'Time_Since_Last_Check_Up', 'Loneliness', 'Health_Rating', 'Annual_Income', 'Days_Poor_Physical_Health', 'Education', 'Social_Emotional_Support', 'General_Health_Personal_Rating', 'Life_Satisfaction', 'Marital_Status']].astype('category')

x_train = x_train.reset_index(drop=True)

# Create kernel
kernel = mf.ImputationKernel(x_train, num_datasets=4)

# Run MICE
kernel.mice(3)

# Return completed data
x_train_imputed = kernel.complete_data()

In [83]:
x_test[['Sex', 'Days_Poor_Mental_Health', 'Age_Category', 'Other_Tobacco_Usage', 'Race', 
        'Time_Since_Last_Check_Up', 'Loneliness', 'Health_Rating', 'Annual_Income', 
        'Days_Poor_Physical_Health', 'Education', 'Social_Emotional_Support', 
        'General_Health_Personal_Rating', 'Life_Satisfaction', 'Marital_Status']] = (
    x_test[['Sex', 'Days_Poor_Mental_Health', 'Age_Category', 'Other_Tobacco_Usage', 'Race', 
            'Time_Since_Last_Check_Up', 'Loneliness', 'Health_Rating', 'Annual_Income', 
            'Days_Poor_Physical_Health', 'Education', 'Social_Emotional_Support', 
            'General_Health_Personal_Rating', 'Life_Satisfaction', 'Marital_Status']]
    .astype('category')
)

x_test = x_test.reset_index(drop=True)

# Use the trained kernel to impute the test set
test_kernel = kernel.impute_new_data(x_test)

# Return completed test data
x_test_imputed = test_kernel.complete_data()

In [84]:
# Checking that MICE worked

In [85]:
x_train_check = x_train_imputed.columns[x_train_imputed.isna().any()].tolist()
print(x_train_check)

[]

In [86]:
x_test_check = x_test_imputed.columns[x_test_imputed.isna().any()].tolist()
print(x_test_check)

[]

## One-Hot Encoding

In [87]:
# Elizabeth Greenan

In [88]:
x_train_imputed.dtypes

BMI                                       float64
Number_of_Children                        float64
Dentist_Visit_Last_Year                   float64
Health_Insurance                          float64
Lung_Cancer_Suspected_Risk                float64
Marijuana_Use_30_Days                     float64
Medical_Visit_Missed_Due_to_Cost          float64
Number_of_Days_Last_Month_Poor_Health     float64
High_Financial_Stress_Burden              float64
Sex                                      category
Has_Disability                            float64
Diabetic_History                          float64
Days_Poor_Mental_Health                  category
Age_Category                             category
Other_Tobacco_Usage                      category
Race                                     category
Total_Drinks_30_days                      float64
Time_Since_Last_Check_Up                 category
Exercise_Outside_Work_Past_Month          float64
Loneliness                               category
Health_Rating                            category
Annual_Income                            category
Days_Poor_Physical_Health                category
Education                                category
Social_Emotional_Support                 category
General_Health_Personal_Rating           category
Life_Satisfaction                        category
Marital_Status                           category
Sugar_Soda_Drinks_Per_Day                 float64
Sugar_Soda_Drinks_Per_Week                float64
Sugar_Soda_Drinks_Per_Month               float64
Non_Soda_Sugar_Drinks_Per_Day             float64
Non_Soda_Sugar_Drinks_Per_Week            float64
Non_Soda_Sugar_Drinks_Per_Month           float64
dtype: object

In [89]:
x_test_imputed.dtypes

BMI                                       float64
Number_of_Children                        float64
Dentist_Visit_Last_Year                   float64
Health_Insurance                          float64
Lung_Cancer_Suspected_Risk                float64
Marijuana_Use_30_Days                     float64
Medical_Visit_Missed_Due_to_Cost          float64
Number_of_Days_Last_Month_Poor_Health     float64
High_Financial_Stress_Burden              float64
Sex                                      category
Has_Disability                            float64
Diabetic_History                          float64
Days_Poor_Mental_Health                  category
Age_Category                             category
Other_Tobacco_Usage                      category
Race                                     category
Total_Drinks_30_days                      float64
Time_Since_Last_Check_Up                 category
Exercise_Outside_Work_Past_Month          float64
Loneliness                               category
Health_Rating                            category
Annual_Income                            category
Days_Poor_Physical_Health                category
Education                                category
Social_Emotional_Support                 category
General_Health_Personal_Rating           category
Life_Satisfaction                        category
Marital_Status                           category
Sugar_Soda_Drinks_Per_Day                 float64
Sugar_Soda_Drinks_Per_Week                float64
Sugar_Soda_Drinks_Per_Month               float64
Non_Soda_Sugar_Drinks_Per_Day             float64
Non_Soda_Sugar_Drinks_Per_Week            float64
Non_Soda_Sugar_Drinks_Per_Month           float64
dtype: object

In [90]:
# Create list of categorical variables for one-hot encoding
categorical_var = ['Sex', 'Days_Poor_Mental_Health', 'Age_Category', 'Other_Tobacco_Usage', 'Race', 'Time_Since_Last_Check_Up', 'Loneliness', 'Health_Rating', 'Annual_Income', 'Days_Poor_Physical_Health', 'Education', 'Social_Emotional_Support', 'General_Health_Personal_Rating', 'Life_Satisfaction', 'Marital_Status']
# One-Hot Encoding on Training Set
encoder = OneHotEncoder(handle_unknown = 'ignore')
encoder.fit(x_train_imputed[categorical_var])
encoded_train = pd.DataFrame(
    encoder.transform(x_train_imputed[categorical_var]).toarray(),
    columns = encoder.get_feature_names_out(categorical_var))
x_train_imputed = pd.concat([x_train_imputed.drop(columns = categorical_var), encoded_train], axis = 1)
x_train_imputed.columns

Index(['BMI', 'Number_of_Children', 'Dentist_Visit_Last_Year',
       'Health_Insurance', 'Lung_Cancer_Suspected_Risk',
       'Marijuana_Use_30_Days', 'Medical_Visit_Missed_Due_to_Cost',
       'Number_of_Days_Last_Month_Poor_Health', 'High_Financial_Stress_Burden',
       'Has_Disability',
       ...
       'Life_Satisfaction_Unknown', 'Life_Satisfaction_Very_dissatified',
       'Life_Satisfaction_Very_satisfied', 'Marital_Status_Divorced',
       'Marital_Status_Married', 'Marital_Status_Member_of_unmarried_couple',
       'Marital_Status_Never_Married', 'Marital_Status_Separated',
       'Marital_Status_Unknown', 'Marital_Status_Widowed'],
      dtype='object', length=104)

In [91]:
# One-Hot Encoding on Test Set
encoded_test = pd.DataFrame(
    encoder.transform(x_test_imputed[categorical_var]).toarray(),
    columns = encoder.get_feature_names_out(categorical_var))
x_test_imputed = pd.concat([x_test_imputed.drop(columns = categorical_var), encoded_test], axis = 1)
x_test_imputed.columns

Index(['BMI', 'Number_of_Children', 'Dentist_Visit_Last_Year',
       'Health_Insurance', 'Lung_Cancer_Suspected_Risk',
       'Marijuana_Use_30_Days', 'Medical_Visit_Missed_Due_to_Cost',
       'Number_of_Days_Last_Month_Poor_Health', 'High_Financial_Stress_Burden',
       'Has_Disability',
       ...
       'Life_Satisfaction_Unknown', 'Life_Satisfaction_Very_dissatified',
       'Life_Satisfaction_Very_satisfied', 'Marital_Status_Divorced',
       'Marital_Status_Married', 'Marital_Status_Member_of_unmarried_couple',
       'Marital_Status_Never_Married', 'Marital_Status_Separated',
       'Marital_Status_Unknown', 'Marital_Status_Widowed'],
      dtype='object', length=104)

In [92]:
# Check that the columns in both training and test set match
set(x_train_imputed.columns) == set(x_test_imputed.columns)

True

In [93]:
# Check that the columns in both training and test set match
set(x_train_unsupervised.columns) == set(x_test_unsupervised.columns)

True

## Center and Scale variables

In [94]:
# Kevin Wilson
# Source: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

In [98]:
scaler = StandardScaler()

scaler.fit(x_train_imputed)
x_train_scaled = pd.DataFrame(scaler.transform(x_train_imputed), columns = x_train_imputed.columns)
x_test_scaled = pd.DataFrame(scaler.transform(x_test_imputed), columns = x_test_imputed.columns)

## Export pre-processed data as CSV files to be used in models

In [99]:
# Elizabeth Greenan
# Source: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html

In [100]:
x_train_scaled.to_csv("../Data/x_train.csv", index = False)
x_test_scaled.to_csv("../Data/x_test.csv", index = False)

In [101]:
y_train.to_csv("../Data/y_train.csv", index = False)
y_test.to_csv("../Data/y_test.csv", index = False)